language: node_js
node_js:
    - "11"
before_install:
    - npm update
script:
    - make install
    - cd Frontend
    - npm run check-eslint-config
    - npm run check-code
    - npm run test-with-cov
    - cd ../Backend
    - npm run test-with-cov
    - cd ../App
    - npm run test-with-cov
notifications:
  email: false
