language: node_js
node_js:
    - node
before_install:
    - npm update
    - npm install -g grpc@1.20.2
script:
    - make install
    - cd Frontend
    - npm run check-eslint-config
    - npm run check-code
    - npm run test-with-cov
    - cd ../Backend
    - npm run test-with-cov
    - cd ../App
    - npm run test-with-cov
notifications:
  email: false
